import numpy as np

types_dict = {
    'poNumber': str,
    'poName': str,
    'poRequisitionerWwid': str,
    'poRequisitionerName': str,
    'poPreparerWwid': str,
    'poPreparerName': str,
    'costCenter': str,
    'costCenterDesc': str,
    'primaryInternalOrder': str,
    'profitCenter': str,
    'generalLedgerAccount': str,
    'generalLedgerAccountDesc': str,
    'projectWbs': str,
    'supplierNumber': str,
    'supplierName': str,
    'supplierEmailAddress': str,
    'poType': str,
    'poStatus': str,
    'poCloseStatus': str,
    'invoicePaidStatus': str,
    'clearingDocumentRef': str,
    'localCurrencyForPoValue': str,
    'documentCurrencyForPoValue': str,
    'localCurrencyForGoodsReceipt': str,
    'documentCurrencyForGoodsReceipt': str,
    'localCurrencyForInvoiceReceipt': str,
    'docCurrencyForInvoiceReceipt': str,
    'poValueInGlobalCurrency': float,
    'poValueInLocalCurrency': float,
    'poValueInDocCurrency': float,
    'gdsReceiptValueInGlobalCurrency': float,
    'gdsReceiptValueInlocalCurrency': float,
    'gdsReceiptValueInDocCurrency': float,
    'invoiceReceiptValueInGlobalCurrency': float,
    'invoiceReceiptValueInLocalCurrency': float,
    'invoiceReceiptValueInDocCurrency': float,
    'aribaBu': str,
    'mrc': str,
    'companyCode': str,
    'legalEntity': str,
    'fsid': str,
    'region': str,
    'businessArea': str,
    'shipTo': str,
    'deliverTo': float,
    'commodityType': str,
    'excludeDownpaymentRequestsForPayments': str,
    'sourceSystemApprovableId': str,
    'matOrSrc': str,
    'requisitionNumber': str,
    'receivableIndicator': str,
    'poLineNumber': float,
    'splitLineNumber': float
}

parse_dates = [
    'poCreationDate',
    'poStartDate',
    'poEndDate',
    'receiptDates',
    'invoiceDates',
    'transactionDate',
    'clearingDateReference',
    'needByDate'
]